// Code generated by tools/projectsync from project.env. DO NOT EDIT.

package buildinfo

// Identity defaults, equal to project.env. The Makefile overrides them at
// link time with -ldflags -X.
var (
	domain  = "chowki.dev"
	owner   = "852hamza"
	repo    = "chowki"
	website = ""
	docs    = ""
)

// Project returns the identity this binary was built with.
func Project() Identity {
	return Identity{Domain: domain, Owner: owner, Repo: repo, Website: website, Docs: docs}
}
