// The guide's sidebar follows its folders, in the order of their
// _category_.json files.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  guide: [{type: 'autogenerated', dirName: '.'}],
};
